spring:
  application:
    name: newfriday
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


app:
  spotify:
    clientBearer: ${SPOTIFY_CLIENT_BEARER}
