spring:
  application:
    name: newfriday
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true


app:
  spotify:
    clientBearer: ${SPOTIFY_CLIENT_BEARER}
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,httpexchanges
    health:
      show-details: always
    httpexchanges:
      enabled: true